# SonarCloud Configuration
# https://docs.sonarsource.com/sonarcloud/advanced-setup/analysis-parameters/

sonar.projectKey=PedroVMota_claude-mcp-server
sonar.projectName=claude-mcp-server

# Source configuration
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11

# Encoding
sonar.sourceEncoding=UTF-8
